default: &default
  adapter: mysql2
  encoding: utf8
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  reconnect: false
  database: taskapp_development
  username: root
  password: taitasu2
  host: localhost

test:
  <<: *default
  database: taskapp_test
  username: root
  password: taitasu2

production:
  <<: *default
  database: taskapp_production
  username: root
  password: taitasu2
