default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || 'taitasu2' %>
  host: <%= ENV['DB_HOST'] || 'db' %>

development:
  <<: *default
  database: <%= ENV['DB_NAME_DEVELOPMENT'] || 'taskapp_development' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] || 'taskapp_test' %>

production:
  <<: *default
  database: <%= ENV['DB_NAME_PRODUCTION'] || 'taskapp_production' %>
